# Generated by Django 3.2.8 on 2021-11-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='numero_paginas',
            field=models.IntegerField(default=1, help_text='numero de paginas de textos', max_length=1000),
            preserve_default=False,
        ),
    ]
