# Generated by Django 3.2.8 on 2021-11-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_libro_numero_paginas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='Ingrese marca de vehiculo', max_length=200)),
                ('cilindraje', models.FloatField(help_text='Ingrese el cilindraje')),
            ],
        ),
    ]
