# Generated by Django 3.2.9 on 2021-11-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_pelicula_ropa_zapatos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropa',
            name='Diseñador',
            field=models.FloatField(default=1, help_text='Ingrese el nombre del diseñador'),
            preserve_default=False,
        ),
    ]
